### ISSUE TITLE
vendor autoload - failed to open

### ISSUE THREAD

**Issue by jaasaria** [davzie/laravel-echo-pusher-walkthrough#1]
after installing composer install,npm install and create db/set env . when migrating my database i encounter this error. can you pls take a look on this. thank you

![error](https://cloud.githubusercontent.com/assets/5240819/21342158/74445068-c6cb-11e6-93c4-f6b5e57bbef5.png)

**Comment by davzie** [comment]
Hey @jaasaria ,

Try deleting the vendor folder entirely and then running `composer install` again from the root of the project.

**Comment by jaasaria** [comment]
thanks now its running.also dude if you have time can you make a video on how to setup laravel vue using webpack. i think i have a problem in my installation thats why im getting an error in my project.

**Comment by davzie** [comment]
@jaasaria I may well do this, there's news Elixir may be getting a rename so I might wait until then, good luck!
